#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EventApp.Resource", IsApplication=true)]

namespace EventApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert_border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cancel_border = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cell_border = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cursor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int default_border = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_group = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_location = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_more = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_person = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_phone = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_search = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_sort = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int panel_border = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int send_border = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int spinner_item = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int admin_panel = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int alert_accounts = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int alert_subtitle = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int alert_title = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int btn_cancel = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int btn_logout = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btn_managers = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int btn_send = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int card_cost = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int card_eclient = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int card_edate = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int card_elocation = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int card_emanager = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int card_epersons = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int card_etype = 2131165191;
			
			// aapt resource value: 0x7f07001d
			public const int card_mname = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int card_mphone = 2131165214;
			
			// aapt resource value: 0x7f070006
			public const int card_title = 2131165190;
			
			// aapt resource value: 0x7f07001a
			public const int event_client = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int event_date = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int event_location = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int event_persons = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int event_type = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int login_button = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int login_textView = 2131165202;
			
			// aapt resource value: 0x7f070020
			public const int managers_list = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int managers_search_field = 2131165215;
			
			// aapt resource value: 0x7f070017
			public const int menu_list = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int menu_more_button = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int menu_search_button = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int menu_search_field = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int menu_sort_button = 2131165203;
			
			// aapt resource value: 0x7f070023
			public const int new_manager_btn = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int new_manager_name = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int new_manager_phone = 2131165218;
			
			// aapt resource value: 0x7f070011
			public const int password_text = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AdminPanel = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CustomCardAlert = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainMenu = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MainMenuCard = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ManagerCard = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ManagersMenu = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Events = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
